name: lifetime_signal
description: Lifetime signal
repository: https://github.com/dorofiykolya/flutter-lifetime-signal
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lifetime: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: